my-website/
├── index.html
├── style.css
└── script.js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Portfolio</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>My Portfolio</h1>
        <nav>
            <ul>
                <li><a href="#about">About</a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <section id="about">
        <h2>About Me</h2>
        <p>This is where you can write a brief introduction about yourself.</p>
    </section>
    <section id="projects">
        <h2>Projects</h2>
        <div class="project">
            <h3>Project 1</h3>
            <p>Description of project 1.</p>
        </div>
        <div class="project">
            <h3>Project 2</h3>
            <p>Description of project 2.</p>
        </div>
    </section>
    <section id="contact">
        <h2>Contact</h2>
        <p>You can contact me at <a href="mailto:your-email@example.com">your-email@example.com</a>.</p>
    </section>
    <footer>
        <p>&copy; 2024 My Portfolio</p>
    </footer>
    <script src="script.js"></script>
</body>
</html>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    line-height: 1.6;
}

header {
    background: #333;
    color: #fff;
    padding: 1rem 0;
    text-align: center;
}

header h1 {
    margin: 0;
}

nav ul {
    list-style: none;
    padding: 0;
}

nav ul li {
    display: inline;
    margin: 0 10px;
}

nav ul li a {
    color: #fff;
    text-decoration: none;
}

section {
    padding: 2rem;
}

#about, #projects, #contact {
    margin: 0 auto;
    max-width: 800px;
}

.project {
    background: #f4f4f4;
    margin: 1rem 0;
    padding: 1rem;
    border: 1px solid #ddd;
}

footer {
    text-align: center;
    padding: 1rem 0;
    background: #333;
    color: #fff;
}
// script.js
document.addEventListener('DOMContentLoaded', () => {
    console.log('Document loaded');
});
cd my-website
git init
git add .
git commit -m "Initial commit"
git remote add origin https://github.com/your-username/my-website.git
git push -u origin master
